### PR TITLE
load weapon component in manifest

### PR DESCRIPTION
**Pull request by BaziForYou**
I know its crazy that how work for me :|
that is not just this it happen for all I know fivem said this
image

but when it just
`**/weaponcomponents.meta`
image

but correct one
image

### CODE REVIEW

**Comment by arthur-rl** [comment]
Can you share your configuration settings? As in the ones you have entered to the program.

**Comment by BaziForYou** [comment]
> Can you share your configuration settings? As in the ones you have entered to the program.

default template sniper rifle with clip and scope components

**Comment by rubbertoe98** [comment]
Please send screenshots of each tab and the exported weapon files, thanks.

**Comment by BaziForYou** [comment]
> Please send screenshots of each tab and the exported weapon files, thanks.

image
image
image
image
image

Exported
https://gofile.io/d/CVhFSY
result
image
fixed with change manifest 
correct 
image

Server build on my test SV: 4315

**Comment by rubbertoe98** [comment]
Thanks, you need to re-name the components to make them "addon" components otherwise it's trying to replace them. 

e.g rename the componenets to `COMPONENT_HUNTER_SCOPE_LARGE` & `COMPONENT_HUNTER_CLIP_01`

**Comment by BaziForYou** [comment]
> Thanks, you need to re-name the components to make them "addon" components otherwise it's trying to replace them.
> 
> e.g rename the components to `COMPONENT_HUNTER_SCOPE_LARGE` & `COMPONENT_HUNTER_CLIP_01`

thanks fix that my fault 👍

**Pull request closed without merging**
